🧹 chore(lint): fixed CSpell

diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -294,7 +294,13 @@ tasks:
 
   spelling:cli:
     cmds:
-      - cmd: '{{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}}'
+      - cmd: |
+          set -e
+          EXIT_CODE=0
+          {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
+          if [ "$EXIT_CODE" != '0' ]; then
+            .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+          fi
         ignore_errors: true
 
   spelling:staged:
@@ -305,7 +311,13 @@ tasks:
       - cmd: |
           STAGED_FILES="$(git diff --cached --name-only)"
           if [ -n "$STAGED_FILES" ]; then
-            {{.NPX_HANDLE}}cspell --no-summary --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} "$STAGED_FILES"
+            set -e
+            EXIT_CODE=0
+            # Must not quote $STAGED_FILES
+            {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
+            if [ "$EXIT_CODE" != '0' ]; then
+              .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+            fi
           fi
         ignore_errors: true
 
