☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/ansible/Taskfile.yml b/.config/taskfiles/ansible/Taskfile.yml
--- a/.config/taskfiles/ansible/Taskfile.yml
+++ b/.config/taskfiles/ansible/Taskfile.yml
@@ -6,6 +6,7 @@ vars:
   MAIN_TASKS_PATH: tasks/main.yml
   META_PATH: meta/main.yml
   MOLECULE_RESULTS_PATH: molecule/.results
+  PRE_SHARED_VAULT_KEY: YTtEnhPWtftHFcP3HneVmz6vX2qMqAwobTDAbvDwrdyunAaDCQ
   REQUIREMENTS_PATH: requirements.yml
   ROLE_NAME: '{{.GALAXY_NAMESPACE}}.{{.GALAXY_ROLE_NAME}}'
   SAMPLE_PROJECT: https://github.com/megabyte-labs/ansible-snapd
@@ -98,6 +99,10 @@ tasks:
       start: Installing the Ansible Galaxy requirements specified in `requirements.yml`
       success: Installed the Ansible Galaxy requirements specified in `requirements.yml`
     cmds:
+      - |
+        if [ -f ~/.netrc ]; then
+          chmod 600 ~/.netrc
+        fi
       - cmd: '{{.PYTHON_HANDLE}} ansible-galaxy install -r requirements.yml --ignore-errors'
         ignore_error: true
     status:
@@ -144,7 +149,7 @@ tasks:
         fi
         jq -r --argjson result "$MERGED_TAGS" '.keywords = $result' package.json > "$TMP"
         mv "$TMP" package.json
-        {{.NPX_HANDLE}}prettier --write package.json > /dev/null
+        prettier --write package.json > /dev/null
         mkdir -p .cache/megabytelabs
         jq -n --argjson result "$RESULT" --argjson gi "$GALAXY_INFO" '$gi | .galaxy_info.galaxy_tags = $result' > .cache/megabytelabs/galaxy-meta.json
         yq eval -P .cache/megabytelabs/galaxy-meta.json > meta/main.yml
@@ -241,38 +246,73 @@ tasks:
       - task: quickstart:demo
 
   quickstart:cli:
+    deps:
+      - :install:software:openssl
+    summary: |
+      # Ansible Quickstart CLI
+
+      Use this task if you already know the inventory file you would like to run the
+      `main.yml` playbook on. The unique feature is that this task will first run
+      `playbooks/init.yml` (and skip any task tagged with `skip_on_init`), reboot,
+      and then run the normal `main.yml`. This allows you to provision a single computer
+      that serves both as the client and host of Ansible (since some software requires
+      reboots).
+
+      {{.QUICKSTART_VAULT_SECURITY}}
     vars:
       INVENTORY: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}inventories/local.yml{{end}}'
       PLAY_PARAMS:
         sh: |
-          if [ -f .cache/playbook-quickstart-demo-called ]; then
+          if [ ! -f ~/.VAULT_PASS_REMOVE_ME ]; then
             echo '--skip-tags "skip_on_init" playbooks/init.yml'
           else
             echo 'main.yml'
           fi
-      VAULT_PASS:
-        sh: |
-          {{if .VAULT_PASS}}echo '{{.VAULT_PASS}}'{{else}}
-          if [ -f ~/.vault_pass ]; then
-            echo '--vault-pass-file ~/.vault_pass'
-          else
-            echo '--ask-vault-pass'
-          fi
-          {{end}}
+      QUICKSTART_VAULT_SECURITY: |
+        ## Ansible Vault Password Security
+
+        To achieve automation wherever possible, we save your Ansible Vault password
+        on disk during the installation process (i.e. to preserve the information
+        inbetween reboots).
+
+        To make it more secure, we employ the following measures:
+        1. The password is forcibly removed anytime the ansible-playbook command fails
+        2. It is passed in via the `ANSIBLE_VAULT_PASSWORD` variable to minimize the possibility
+        of the password displaying in the terminal or getting added to the command history.
+        3. It is stored in `~/.VAULT_PASSWORD` so you can easily spot it if something
+        goes wrong.
+    env:
+      ANSIBLE_VAULT_PASSWORD_FILE: ~/.VAULT_PASSWORD
+      QUICKSTART_VAULT_SECURITY: '{{.QUICKSTART_VAULT_SECURITY}}'
     log:
       error: Error occurred while running the Ansible play
       start: Running the Ansible play locally
       success: Successfully ran the Ansible play locally
     cmds:
-      - |
-        if [ ! -f .cache/playbook-quickstart-demo-called ]; then
-          echo "cd $PWD" >> ~/.config/ansible-playbook-continue-command
-          echo 'task ansible:quickstart:cli -- {{.INVENTORY}}' >> ~/.config/ansible-playbook-continue-command
-          mkdir .cache && touch .cache/playbook-quickstart-demo-called
-          .config/log info 'Prompting for sudo / vault password'
-        fi
-      - >
-        {{.PYTHON_HANDLE}}ansible-playbook {{.VAULT_PASS}} -i {{.INVENTORY}} {{.PLAY_PARAMS}}
+      - cmd: |
+          if [ ! -f "$ANSIBLE_VAULT_PASSWORD_FILE" ]; then
+            .config/log info 'Adding `~/ANSIBLE_PLAYBOOK_CONTINUE.sh` to run on reboot'
+            echo "#!/usr/env/bin bash" > ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo "" > ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo "cd $PWD" >> ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo 'task ansible:quickstart:cli -- {{.INVENTORY}}' >> ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            if [ -z "$ANSIBLE_VAULT_PASSWORD" ]; then
+              MD_TMP="$(mktemp)"
+              echo "$QUICKSTART_VAULT_SECURITY" > "$MD_TMP"
+              .config/log md "$MD_TMP"
+              .config/log info 'Read about security measures above.'
+              .config/log prompt 'What is your Ansible Vault password?'
+              export ANSIBLE_VAULT_PASSWORD="$(.config/log password 'Enter Vault password (leave empty if there is not a password)..')"
+            fi
+          fi
+          .config/log info 'Writing the `ANSIBLE_VAULT_PASSWORD` to temporary file in user home directory'
+          echo "$ANSIBLE_VAULT_PASSWORD" > ~/.VAULT_PASSWORD
+          {{.PYTHON_HANDLE}}ansible-playbook -i {{.INVENTORY}} {{.PLAY_PARAMS}}
+        ignore_error: true
+      - sleep 5
+      - .config/log info 'Ensuring the password (if provided) is forcibly removed'
+      - rm -f ~/.VAULT_PASSWORD
+      - rm -f ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
 
   quickstart:demo:
     cmds:
@@ -293,15 +333,94 @@ tasks:
     deps:
       - :install:pipx:getmac
       - :install:software:jq
+    summary: |
+      # Quickstart Mapping
+
+      This task is a helper task that attempts to automatically select the appropriate
+      Ansible inventory based on the MAC address. If the mapping entry is not already
+      saved, this task will guide the user through a series of prompts.
+
+      {{.MAC_ADDRESS_EXPLANATION}}
+    env:
+      MAC_ADDRESS_EXPLANATION: '{{.MAC_ADDRESS_EXPLANATION}}'
+    vars:
+      INVENTORY_OPTIONS:
+        sh: echo "\"inventories"$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"inventories")')"\""
+      INVENTORY_OPTIONS_LENGTH:
+        sh: find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | length'
+      MAC_ADDRESS_EXPLANATION: |
+        ## Mapping MAC Addresses to Inventory Files
+
+        In order to achieve a completely automated flow, we have the ability
+        to define a map of MAC addresses and inventory files in the `files/`
+        folder.
+
+        You can get your MAC address by using the `getmac` program that this
+        task installs or you can run the following on Linux:
+
+        ```
+        cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address
+        ```
+
+        On Windows, if you are provisioning with Docker (the default "Quick Start" method)
+        and if you make sure you are running it on either a clean system or have no other
+        Docker containers running, then the MAC address will be:
+
+        ```
+        02:42:ac:11:00:02
+        ```
+
+        If you wanted to run the Quick Start method on Windows, you could create a file in
+        `files/inventory-map.json` that looks something like this:
+
+        ```
+        {
+          "02:42:ac:11:00:02": "inventories/workstation.yml"
+        }
+        ```
+
+        This configuration would instruct the script to automatically use the `inventories/workstation.yml`
+        inventory. If your MAC address is missing, the script will open an interactive prompt and include
+        the ability to save your MAC address to the file for later use.
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         # MAC_ADDRESS="$(cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address)" # Does not work on macOS
         MAC_ADDRESS="$(getmac)"
         TARGET_INV="$(jq --arg macAddress "$MAC_ADDRESS" -r '.[$macAddress]' files/inventory-map.json)"
-        if [ "$TARGET_INV" != 'null' ]; then
+        if [[ "$TARGET_INV" == '' ]]; then
+          .config/log warn 'Initializing `files/inventory-map.json` since it appears to be an empty file'
+          echo '{}' > files/inventory-map.json
+        fi
+        if [ "$TARGET_INV" != 'null' ] && [ "$TARGET_INV" != '' ]; then
+          .config/log info "Provisioning with "'`'"$TARGET_INV"'`'
           task ansible:quickstart:cli -- "$TARGET_INV"
         else
-          .config/log error "MAC address missing from inventory-map.json ($MAC_ADDRESS)"
+          MD_TMP="$(mktemp)"
+          echo "$MAC_ADDRESS_EXPLANATION" > "$MD_TMP"
+          .config/log md "$MD_TMP"
+          .config/log warn "MAC address missing from inventory-map.json ($MAC_ADDRESS). Details printed above."
+          if [ '{{.INVENTORY_OPTIONS_LENGTH}}' != '0' ]; then
+            .config/log prompt 'Given the information above, would you like to save your MAC address to the `files/inventory-map.json` file?'
+            if .config/log confirm 'Save MAC address?'; then
+              .config/log prompt 'Which inventory file would you like the associate the MAC address with?'
+              INVENTORY_FILE="$(.config/log choose {{.INVENTORY_OPTIONS}})"
+              TMP="$(mktemp)"
+              .config/log info 'Generating new `files/inventory-map.json` file'
+              jq --arg inventory "$INVENTORY_FILE" --arg macaddr "$MAC_ADDRESS" '.[$macaddr] = $inventory' files/inventory-map.json > "$TMP"
+              mv "$TMP" files/inventory-map.json
+              .config/log success "Successfully associated the selected inventory with this machine's MAC address (remember to git add / commit)"
+              task ansible:quickstart:cli -- "$INVENTORY_FILE"
+            else
+              .config/log prompt 'Which inventory file would you like to use?'
+              INVENTORY_FILE="$(.config/log choose {{.INVENTORY_OPTIONS}})"
+              task ansible:quickstart:cli -- "$INVENTORY_FILE"
+            fi
+          else
+            .config/log error 'There are no inventories defined in the `inventories/` folder.'
+            .config/log info 'Try running `task environment` to link to sample environments'
+            exit 1
+          fi
         fi
     status:
       - '[ ! -f files/inventory-map.json ]'
diff --git a/.config/taskfiles/fix/Taskfile.yml b/.config/taskfiles/fix/Taskfile.yml
--- a/.config/taskfiles/fix/Taskfile.yml
+++ b/.config/taskfiles/fix/Taskfile.yml
@@ -45,7 +45,7 @@ tasks:
       start: Auto-fixing with ESLint
       success: ESLint fixing appears to have corrected all the issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - 'unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
+      - 'unbuffer eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
         --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}'
       - |
         if [ '{{.ESLINT_FIX_RECURSIVE}}' == 'true' ]; then
@@ -54,7 +54,7 @@ tasks:
             COUNT=$((COUNT + 1))
             if grep 'potentially fixable with the `--fix` option' < {{.ESLINT_LOG}} > /dev/null; then
               COUNT="$COUNT"
-              unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
+              unbuffer eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
               --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}
             fi
           done
@@ -74,7 +74,7 @@ tasks:
       success: Successfully auto-fixed modified files with ESLint
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   go:
@@ -123,8 +123,8 @@ tasks:
       start: Linting JSON with ESLint
       success: ESLint has fixed all of the JSON issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
-        --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
+        --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   markdown:
     deps:
@@ -181,6 +181,7 @@ tasks:
       success: Finished performing miscellaneous fixes{{if .CLI_ARGS}} on `{{.CLI_ARGS}}`{{end}}
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         function misc() {
           fix-byte-order-marker "$1"
           mixed-line-ending --fix=lf "$1"
@@ -276,10 +277,12 @@ tasks:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
       - cmd: |
-          {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+          prettier --plugin node_modules/prettier-plugin-toml-fixed --ignore-path {{.PRETTIERIGNORE_CONFIG}} \
+          --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
           if [ -n "$EXIT_CODE" ]; then
-            .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
-            prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+            .config/log warn 'Failed to run `prettier` - falling back to `prettier`'
+            prettier --plugin node_modules/prettier-plugin-toml-fixed --ignore-path {{.PRETTIERIGNORE_CONFIG}} \
+            --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
           fi
         ignore_error: true
 
@@ -310,6 +313,7 @@ tasks:
       success: Fixed {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}} with `black`
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         {{if .CLI_ARGS}}
           pyformat -i {{.CLI_ARGS}}
           isort --overwrite-in-place {{.CLI_ARGS}}
@@ -360,10 +364,10 @@ tasks:
       - |
         .config/log warn 'This is an experimental fix method - please manually inspect and test the scripts'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff {{.CLI_ARGS}} | git apply
+          shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff {{.CLI_ARGS}} | git apply
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
-            -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
+            -print0 | xargs -0 shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
         {{end}}
 
   spelling:markdown:
@@ -404,6 +408,7 @@ tasks:
       success: Successfully ran the `toml-sort` auto-fixer
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         {{if .CLI_ARGS}}
         if [ -f '{{.CLI_ARGS}}' ]; then
           toml-sort -i --all {{.CLI_ARGS}}
@@ -433,8 +438,8 @@ tasks:
       start: Attempting to auto-fix any XML files with ESLint
       success: Any XML files present in the project were successfully fixed/validated by ESLint
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
-        --format pretty --ext .xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
+        --format pretty --ext .xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     desc: Auto-format and sort YML files
@@ -518,5 +523,5 @@ tasks:
       start: Ensuring YML file(s) are in order specified in configuration
       success: Successfully ensured YML file order
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --fix --cache
-        --cache-location .cache/eslintcache --ext yml,yaml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --format pretty --fix --cache
+        --cache-location .cache/eslintcache --ext yml,yaml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -42,7 +42,9 @@ tasks:
       start: Linting project with Ansible Lint
       success: Validated project with Ansible Lint
     cmds:
-      - ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
 
   any:
     deps:
@@ -53,11 +55,13 @@ tasks:
       error: Errors were reported by the global linters for `{{.CLI_ARGS}}`
       start: Linting `{{.CLI_ARGS}}` with global linters
     cmds:
-      - blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}
-      - check-merge-conflict {{.CLI_ARGS}}
-      - check-added-large-files {{.CLI_ARGS}}
-      - check-symlinks {{.CLI_ARGS}}
-      - destroyed-symlinks {{.CLI_ARGS}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-merge-conflict {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-added-large-files {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && check-symlinks {{.CLI_ARGS}}
+      - PATH="$PATH:$HOME/.local/bin" && destroyed-symlinks {{.CLI_ARGS}}
 
   codeclimate:
     deps:
@@ -125,7 +129,7 @@ tasks:
           TMP="$(mktemp)"
           COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
           .config/log info 'Linting commit message (with emoji stripped)'
-          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_HANDLE}}commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
+          echo "$COMMIT_MSG_NOEMOJI" | commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
         elif [ '{{.CLI_ARGS}}' == '.git/MERGE_MSG' ]; then
           .config/log info 'Bypassing commitlint since the message is a merge message'
         fi
@@ -234,7 +238,7 @@ tasks:
       success: Successfully passed the ESLint test (please still address warnings)
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   eslint:staged:
@@ -250,7 +254,7 @@ tasks:
       success: Successfully linted modified files with ESLint
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   eslint:warn-all:
@@ -271,7 +275,7 @@ tasks:
       - >
         ESLINT_TMP="$(mktemp)"
 
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format summary --cache
+        eslint -c package.json --no-eslintrc --format summary --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} |
         tee "$ESLINT_TMP"
 
@@ -318,7 +322,7 @@ tasks:
       success: Successfully passed ESLint checks for {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}JavaScript/TypeScript files{{end}}
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
+        eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
         --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   lint-staged:
@@ -331,7 +335,7 @@ tasks:
       success: The staged files appear to be good!
     cmds:
       - |
-        {{.NPX_HANDLE}}lint-staged || LINT_EXIT_CODE="$?"
+        lint-staged || LINT_EXIT_CODE="$?"
         if [ -n "$LINT_EXIT_CODE" ]; then
           .config/log error 'Linting failed!'
           .config/log info 'If necessary, you can bypass this pre-commit hook by running `git commit --no-verify`. Please try to fix the errors first.'
@@ -414,9 +418,9 @@ tasks:
       success: Prettier successfully finished
     cmds:
       - |
-        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
         if [ -n "$EXIT_CODE" ]; then
-          .config/log warn 'Failed to lint with `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          .config/log warn 'Failed to lint with `prettier` - falling back to `prettier`'
           prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
         fi
 
@@ -460,7 +464,9 @@ tasks:
       start: Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}the project{{end}} with flake8
       success: flake8 validation was successful
     cmds:
-      - flake8 {{.CONFIG_COMMAND}}{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        flake8 {{.CONFIG_COMMAND}}{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   python:deps:flake8:
     cmds:
@@ -509,10 +515,10 @@ tasks:
       - |
         .config/log info 'Linting with Shellcheck'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
+          shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
-          -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}}
+          -print0 | xargs -0 -r -n1 shellcheck -e {{.SHELLCHECK_EXCLUDE}}
         {{end}}
 
   spelling:
@@ -546,7 +552,7 @@ tasks:
       - cmd: |
           set -e
           EXIT_CODE=0
-          {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
+          cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
           if [ "$EXIT_CODE" != '0' ]; then
             .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
           fi
@@ -584,7 +590,7 @@ tasks:
             EXIT_CODE=0
             .config/log info 'Running a spell-check on staged files with `cspell`'
             # Must not quote $STAGED_FILES
-            {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
+            cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
             if [ "$EXIT_CODE" != '0' ]; then
               .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
             fi
@@ -610,7 +616,9 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}`{{.CLI_ARGS}}` is valid TOML{{else}}the project'\''s TOML files are valid{{end}}
       success: The TOML appears to be valid!
     cmds:
-      - check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   vagrant:
     deps:
@@ -652,7 +660,9 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid XML{{else}}the project contains only valid XML{{end}}
       success: The XML appears to be valid
     cmds:
-      - check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     deps:
@@ -683,4 +693,6 @@ tasks:
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with `yamllint`
       success: No issues were detected by `yamllint`
     cmds:
-      - yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
